project:
  type: website
  output-dir: docs

website:
  title: "Uriel Santa Cruz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume & Contact
    right:
      - icon: github
        href: https://github.com/yourusername
      - icon: linkedin
        href: https://www.linkedin.com/in/yourlinkedin
      - icon: envelope
        href: mailto:youremail@example.com

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full

editor: visual