---
title: "About"
---

# Who I am

I’m a Statistics & Data Science student at UCLA with a strong interest in using data to uncover meaningful patterns and communicate insights clearly. My interest in statistics began in high school when I discovered the U.S. Bureau of Labor Statistics website. I was fascinated by how freely accessible data could help people make real decisions about education, careers, and the future.

That experience showed me how powerful data can be when it is organized and communicated effectively. Since then, I’ve been interested in projects that combine technical analysis with real-world relevance.

## Education

**University of California, Los Angeles (UCLA)**\
B.S. in Statistics & Data Science\
Expected Graduation: Month Year

**Relevant Coursework** - Regression Analysis - Machine Learning / Data Analysis - Statistical Computing - Data Visualization - Linear Algebra - Probability / Mathematical Statistics

## What I’m Interested In

Many of the problems that interest me most are connected to digital media and the internet. I enjoy exploring questions related to social media platforms, online content ecosystems, and the entertainment industry. Platforms like YouTube, Netflix, and Spotify are built on data-driven systems, and I find it fascinating to study the patterns behind how content spreads, trends emerge, and audiences engage with media.

## Outside the Classroom

Outside of coursework, I enjoy working on collaborative data science projects and helping others learn technical tools. As a workshop lead for the National Student Data Corps (NSDC), I have presented SQL and Tableau workshops to groups of students, focusing on making data tools more accessible for beginners.

I’m also a PC gamer and enjoy building computers where I'v actually built my own gaming PC using scholarship funds and savings. I’m a big fan of animated films and appreciate the years of technical and creative work that go into producing them.

I also enjoy working on unconventional data projects. One thing I love about data science is that it can be applied almost anywhere even to unexpected data sets (saw one applied to UFO's, which was fascinating!)
